import 'package:flutter/material.dart';

import '../../../core/theme/react_colors.dart';

enum ReactVariantMechanic {
  command,
  target,
  grid,
  memory,
  tether,
  overload,
}

enum ReactVariantMode {
  // Original Mode Lab library. Hidden entries stay here so old local stats keep
  // their stable enum names even when a mode is switched off.
  phantom,
  mosaic,
  accel,
  titan,
  beacon,
  collapse,
  magnet,
  illusion,
  checkpoint,
  reactor,
  nexus,
  prism,
  memory,
  hunter,
  ascent,
  fracture,
  tempest,
  chain,
  survivor,
  decoder,
  stealth,
  snap,
  vortex,
  timedrop,
  echo,
  orbit,
  fuse,
  shuffle,
  pulse,
  glitch,
  zenith,
  blackout,
  ricochet,
  tether,
  overload,
  lockstep,

  // Mode Lab wave 2.
  harpoon,
  dualcast,
  sentry,
  railrun,
  parallax,
  anchor,
  shockwave,
  hush,
  gateline,
  tidebreak,
  scatter,
  sparkgrid,
  phaseshift,
  barrage,
  monoline,
  rewind,
  crucible,
  vantage,
  catalyst,
  offset,
  barricade,
  skyhook,
  pendulum,
  shadowlink,
  breaker,
  waveline,
  splice,
  thruster,
  frostline,
  pinpoint,
  riftstep,
  corridor,
  sidewinder,
  hinge,
  rampart,
  fadeout,
}

class ReactVariantSpec {
  const ReactVariantSpec({
    required this.title,
    required this.badge,
    required this.subtitle,
    required this.detail,
    required this.rules,
    required this.color,
    required this.icon,
    this.mechanic = ReactVariantMechanic.command,
    this.enabled = true,
  });

  final String title;
  final String badge;
  final String subtitle;
  final String detail;
  final String rules;
  final Color color;
  final IconData icon;
  final ReactVariantMechanic mechanic;
  final bool enabled;
}

const _orange = Color(0xFFFF8A35);
const _cyan = Color(0xFF37D6E8);
const _pink = Color(0xFFFF4F91);

const Map<ReactVariantMode, ReactVariantSpec> _activeSpecs = {
  ReactVariantMode.phantom: ReactVariantSpec(
    title: 'PHANTOM',
    badge: 'GHOST CUES',
    subtitle: 'Prompts flash, then disappear.',
    detail: 'INSTANT RECALL  •  QUICK EYES',
    rules: 'Read the command while it flashes. The cue disappears after half a second, but the timer keeps running. Perform the remembered gesture before time expires.',
    color: ReactColors.electricBlueBright,
    icon: Icons.visibility_off_rounded,
  ),
  ReactVariantMode.mosaic: ReactVariantSpec(
    title: 'MOSAIC',
    badge: 'GRID MODE',
    subtitle: 'Tiny panels fire different cues.',
    detail: 'SCAN SPEED  •  MICRO FOCUS',
    rules: 'Original: a 3×3 panel grid lights one cue at a time. Tap the live panel before it moves. Wrong panels cost a life. Pressure Grid: all nine tiles slowly fill at different rates; tap tiles to drain them before the entire grid fills.',
    color: ReactColors.coral,
    icon: Icons.grid_view_rounded,
    mechanic: ReactVariantMechanic.grid,
  ),
  ReactVariantMode.illusion: ReactVariantSpec(
    title: 'ILLUSION',
    badge: 'OPTICAL',
    subtitle: 'Visual tricks distort every cue.',
    detail: 'TRICK SIGHT  •  TRUST SKILL',
    rules: 'The command remains truthful while its visual presentation fully rotates, blinks, scales, mirrors and shifts. Ignore the distortion and perform the real gesture.',
    color: ReactColors.purple,
    icon: Icons.visibility_rounded,
  ),
  ReactVariantMode.memory: ReactVariantSpec(
    title: 'MEMORY',
    badge: 'RECALL',
    subtitle: 'Recall a growing command chain.',
    detail: 'STACKED PATTERNS  •  NO HINTS',
    rules: 'Watch a growing sequence across four high-contrast pads, then repeat the entire chain in order. Each clear adds one more step.',
    color: ReactColors.electricBlueBright,
    icon: Icons.psychology_alt_rounded,
    mechanic: ReactVariantMechanic.memory,
  ),
  ReactVariantMode.tempest: ReactVariantSpec(
    title: 'TEMPEST',
    badge: 'STORM',
    subtitle: 'Modifiers shift in chaotic waves.',
    detail: 'SURPRISE RULES  •  TURBULENCE',
    rules: 'Every four clears the storm changes rule: SPEED, BLACKOUT, REVERSE or PULSE. The active rule is shown with a large colour-coded icon and one-word cue so it can be read instantly.',
    color: _orange,
    icon: Icons.cyclone_rounded,
  ),
  ReactVariantMode.vortex: ReactVariantSpec(
    title: 'VORTEX',
    badge: 'SPIN',
    subtitle: 'Targets spiral inward as you react.',
    detail: 'SHRINKING SPACE  •  PRESSURE',
    rules: 'Tap a target that spirals toward the centre. Every clear randomises its start phase, direction, angular speed and inward speed so no path repeats.',
    color: ReactColors.purple,
    icon: Icons.blur_circular_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.timedrop: ReactVariantSpec(
    title: 'TIMEDROP',
    badge: 'TIME GAIN',
    subtitle: 'Perfect streaks earn extra time.',
    detail: 'BONUS CLOCK  •  STREAK PLAY',
    rules: 'Start with a limited run clock. Every five-command perfect streak adds bonus time. A miss breaks the streak but the clock keeps falling.',
    color: _cyan,
    icon: Icons.more_time_rounded,
  ),
  ReactVariantMode.glitch: ReactVariantSpec(
    title: 'GLITCH',
    badge: 'DECOY MODE',
    subtitle: 'Fake prompts try to fool you.',
    detail: 'UI TRICKS  •  FOCUS TEST',
    rules: 'Red fake prompts flash before some real commands. Do nothing during FAKE, then react to the green LIVE prompt that follows.',
    color: ReactColors.coral,
    icon: Icons.art_track_rounded,
  ),
  ReactVariantMode.blackout: ReactVariantSpec(
    title: 'BLACKOUT',
    badge: 'LOW LIGHT',
    subtitle: 'Prompts vanish between flashes.',
    detail: 'MEMORY TEST  •  NO PANIC',
    rules: 'The command repeatedly flashes on and off. Remember it through the dark interval and perform the gesture before the overall timer expires.',
    color: ReactColors.purple,
    icon: Icons.dark_mode_rounded,
  ),
  ReactVariantMode.ricochet: ReactVariantSpec(
    title: 'RICOCHET',
    badge: 'BOUNCE',
    subtitle: 'Targets rebound around the ring.',
    detail: 'DEFLECT PATHS  •  QUICK CORRECTION',
    rules: 'Track and tap a bouncing target before the timer expires. Every successful hit generates a completely new random start point, direction and speed.',
    color: _cyan,
    icon: Icons.sports_baseball_rounded,
    mechanic: ReactVariantMechanic.target,
  ),

  ReactVariantMode.harpoon: ReactVariantSpec(
    title: 'HARPOON',
    badge: 'PULL LINE',
    subtitle: 'Latch onto moving cues with precise pulls.',
    detail: 'TRACK  •  GRAB  •  PULL',
    rules: 'A cue moves around the arena. Touch it to latch on, then drag it into the glowing capture ring before the line snaps or the timer expires. Missing the cue or releasing outside the ring costs a life.',
    color: ReactColors.electricBlueBright,
    icon: Icons.north_east_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.dualcast: ReactVariantSpec(
    title: 'DUALCAST',
    badge: 'SPLIT FLOW',
    subtitle: 'Two commands alternate between split halves.',
    detail: 'LEFT / RIGHT  •  RAPID SWITCH',
    rules: 'The arena is split in two. Commands alternate between the left and right half. Perform the displayed gesture on the lit half only; input on the wrong half is a miss.',
    color: _pink,
    icon: Icons.call_split_rounded,
  ),
  ReactVariantMode.sentry: ReactVariantSpec(
    title: 'SENTRY',
    badge: 'WATCH FIRE',
    subtitle: 'Only react when the scanner goes live.',
    detail: 'SCAN  •  WAIT  •  FIRE',
    rules: 'A scanner sweeps continuously around the arena. Tap only while the beam crosses the green live sector. Early or late taps cost a life and the live sector relocates every clear.',
    color: ReactColors.lime,
    icon: Icons.radar_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.railrun: ReactVariantSpec(
    title: 'RAILRUN',
    badge: 'LANE READ',
    subtitle: 'Inputs travel fixed lanes across the arena.',
    detail: '3 LANES  •  INTERCEPT FAST',
    rules: 'Targets enter from the left on one of three fixed rails and race across the arena. Tap the live target before it reaches the far edge. Speed and simultaneous traffic increase with score.',
    color: _orange,
    icon: Icons.multiple_stop_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.parallax: ReactVariantSpec(
    title: 'PARALLAX',
    badge: 'DEPTH READS',
    subtitle: 'Foreground and background cues drift apart.',
    detail: 'DEPTH  •  ALIGNMENT  •  FOCUS',
    rules: 'A bright foreground marker and dim background marker drift at different speeds. Tap when the two layers overlap inside the alignment window; acting while they are separated is a miss.',
    color: ReactColors.purple,
    icon: Icons.layers_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.anchor: ReactVariantSpec(
    title: 'ANCHOR',
    badge: 'FIXED TOUCH',
    subtitle: 'Hold your point while another action triggers.',
    detail: 'HOLD + ACT  •  MULTITOUCH',
    rules: 'Keep one finger held on the anchor pad. While maintaining contact, use another finger to hit each live target. Releasing the anchor or hitting a target without the anchor held costs a life.',
    color: _cyan,
    icon: Icons.anchor_rounded,
    mechanic: ReactVariantMechanic.tether,
  ),
  ReactVariantMode.shockwave: ReactVariantSpec(
    title: 'SHOCKWAVE',
    badge: 'WAVE TIMING',
    subtitle: 'React on expanding rings at the perfect edge.',
    detail: 'EXPAND  •  EDGE WINDOW  •  TAP',
    rules: 'A ring expands from the centre toward a fixed outer target ring. Tap when the moving wave reaches the target edge. The timing window narrows and wave speed changes after every clear.',
    color: ReactColors.electricBlueBright,
    icon: Icons.radar_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.hush: ReactVariantSpec(
    title: 'HUSH',
    badge: 'QUIET FOCUS',
    subtitle: 'Low-signal prompts whisper into view and vanish.',
    detail: 'FAINT CUES  •  QUICK RECALL',
    rules: 'Gesture commands fade in at very low contrast, remain readable only briefly, then disappear. Read the cue and perform the remembered gesture before its timer expires.',
    color: ReactColors.purple,
    icon: Icons.multiline_chart_rounded,
  ),
  ReactVariantMode.gateline: ReactVariantSpec(
    title: 'GATELINE',
    badge: 'OPEN WINDOW',
    subtitle: 'Act only when moving gates align.',
    detail: 'ALIGN  •  OPEN  •  STRIKE',
    rules: 'Two moving gate bars repeatedly create and close a narrow opening. Tap only while their openings overlap. The gate speeds and opening sizes randomise after every success.',
    color: ReactColors.lime,
    icon: Icons.view_week_outlined,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.tidebreak: ReactVariantSpec(
    title: 'TIDEBREAK',
    badge: 'FLOW READ',
    subtitle: 'Rising zones change where actions are safe.',
    detail: 'MOVING SAFE ZONE  •  ADAPT',
    rules: 'Three horizontal zones fill and drain like a rising tide. Only the highlighted safe zone accepts input. Tap its live target before the tide moves to the next zone.',
    color: _cyan,
    icon: Icons.waves_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.scatter: ReactVariantSpec(
    title: 'SCATTER',
    badge: 'TRACK SPLIT',
    subtitle: 'Targets burst apart and reform under pressure.',
    detail: 'SPLIT  •  TRACK  •  REFORM',
    rules: 'A target cluster bursts into several moving fragments. Track the highlighted fragment and tap it before the pieces reform. Fragment count and spread speed rise with score.',
    color: _orange,
    icon: Icons.scatter_plot_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.sparkgrid: ReactVariantSpec(
    title: 'SPARKGRID',
    badge: 'POWER READ',
    subtitle: 'A charging grid lights the valid tiles.',
    detail: '3×3 GRID  •  CHARGE CONTROL',
    rules: 'Nine tiles charge independently. Tap glowing fully charged tiles to discharge them. A charged tile that overloads becomes dangerous; if three tiles overload at once the run ends.',
    color: _pink,
    icon: Icons.grid_on_rounded,
    mechanic: ReactVariantMechanic.grid,
  ),
  ReactVariantMode.phaseshift: ReactVariantSpec(
    title: 'PHASESHIFT',
    badge: 'STATE SWAP',
    subtitle: 'Cues flip between solid and ghost states.',
    detail: 'SOLID = ACT  •  GHOST = WAIT',
    rules: 'The same command flickers between SOLID and GHOST. Perform it only while solid. Input during a ghost phase costs a life. State timing randomises every round.',
    color: ReactColors.electricBlueBright,
    icon: Icons.contrast_rounded,
  ),
  ReactVariantMode.barrage: ReactVariantSpec(
    title: 'BARRAGE',
    badge: 'BURST READ',
    subtitle: 'Micro-bursts of commands arrive in volleys.',
    detail: '3–6 COMMANDS  •  NO PAUSE',
    rules: 'Commands arrive in rapid volleys. Clear every command in the burst before a short recovery beat. Each completed volley adds another command or shortens the window.',
    color: _pink,
    icon: Icons.fast_forward_rounded,
  ),
  ReactVariantMode.monoline: ReactVariantSpec(
    title: 'MONOLINE',
    badge: 'ONE PATH',
    subtitle: 'Follow one moving line of prompts only.',
    detail: 'TRACK LINE  •  IGNORE NOISE',
    rules: 'Several guide lines cross the arena, but only one is live. A target travels along the live line. Track that path and tap the target before it reaches the endpoint.',
    color: _cyan,
    icon: Icons.timeline_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.rewind: ReactVariantSpec(
    title: 'REWIND',
    badge: 'RECALL LOOP',
    subtitle: 'Repeat a flashed sequence in reverse order.',
    detail: 'WATCH  •  REVERSE  •  REPEAT',
    rules: 'Watch a sequence light across four pads. When playback ends, reproduce the entire sequence from last step to first. Each clear adds one new step.',
    color: ReactColors.lime,
    icon: Icons.fast_rewind_rounded,
    mechanic: ReactVariantMechanic.memory,
  ),
  ReactVariantMode.crucible: ReactVariantSpec(
    title: 'CRUCIBLE',
    badge: 'HEAT CLIMB',
    subtitle: 'Pressure climbs the longer you hesitate.',
    detail: 'HEAT  •  FAST DECISIONS',
    rules: 'Heat rises continuously while a command is waiting. Correct input vents heat based on reaction speed. Hesitate too long and the reactor reaches maximum heat, ending the run.',
    color: _orange,
    icon: Icons.local_fire_department_rounded,
  ),
  ReactVariantMode.vantage: ReactVariantSpec(
    title: 'VANTAGE',
    badge: 'ANGLE READ',
    subtitle: 'Find the live cue from shifting angles.',
    detail: 'ROTATE  •  IDENTIFY  •  TAP',
    rules: 'Several cues orbit the centre at different angles. Only the cue facing the bright vantage marker is live. Tap that cue before the formation rotates again.',
    color: ReactColors.purple,
    icon: Icons.view_in_ar_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.catalyst: ReactVariantSpec(
    title: 'CATALYST',
    badge: 'BUILD STATE',
    subtitle: 'Perfect inputs upgrade the next rule instantly.',
    detail: 'PERFECT = EVOLVE  •  ADAPT',
    rules: 'Clear gesture commands normally. A very fast PERFECT clear upgrades the next round with a harder state: shorter time, hidden cue, reverse swipe or pulse-only input. Non-perfect clears return to the base state.',
    color: ReactColors.electricBlueBright,
    icon: Icons.diamond_rounded,
  ),
  ReactVariantMode.offset: ReactVariantSpec(
    title: 'OFFSET',
    badge: 'AIM CORRECT',
    subtitle: 'Prompts appear away from their true hit zone.',
    detail: 'READ OFFSET  •  CORRECT AIM',
    rules: 'The visible prompt appears displaced from its real hit zone. A faint direction line shows the offset. Tap the true crosshair location rather than the decoy prompt.',
    color: _pink,
    icon: Icons.gps_not_fixed_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.barricade: ReactVariantSpec(
    title: 'BARRICADE',
    badge: 'ROUTE FIND',
    subtitle: 'Blocked lanes force fast route changes.',
    detail: '3 LANES  •  BLOCKED PATHS',
    rules: 'A target advances through three lanes while barricades close one or two routes. Tap the target only after it enters an open lane. Barricades reshuffle every round.',
    color: ReactColors.lime,
    icon: Icons.block_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.skyhook: ReactVariantSpec(
    title: 'SKYHOOK',
    badge: 'DROP READ',
    subtitle: 'Catch descending cues before they escape.',
    detail: 'FALLING TARGETS  •  INTERCEPT',
    rules: 'Live cues drop from random positions at changing speeds. Tap each falling cue before it crosses the bottom escape line. Missed catches cost a life.',
    color: _orange,
    icon: Icons.south_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.pendulum: ReactVariantSpec(
    title: 'PENDULUM',
    badge: 'ARC TIMING',
    subtitle: 'A swinging cue demands arc-perfect timing.',
    detail: 'SWING  •  CENTRE WINDOW  •  TAP',
    rules: 'A cue swings through a wide arc. Tap when it passes through the bright centre timing zone. Swing speed, direction and arc width vary after each clear.',
    color: ReactColors.purple,
    icon: Icons.device_hub_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.shadowlink: ReactVariantSpec(
    title: 'SHADOWLINK',
    badge: 'PAIR READ',
    subtitle: 'A hidden partner cue mirrors the real one.',
    detail: 'MIRROR SPACE  •  HIT SHADOW',
    rules: 'One bright cue is visible. Its hidden partner sits at the exact mirrored position across the arena. Tap the invisible partner location, not the visible cue.',
    color: _cyan,
    icon: Icons.polyline_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.breaker: ReactVariantSpec(
    title: 'BREAKER',
    badge: 'LAYER HIT',
    subtitle: 'Crack layered shields in the right order.',
    detail: 'OUTER → INNER  •  SPEED',
    rules: 'A shield contains three concentric layers. Tap the highlighted break point on the outer layer, then middle, then core before the shield rebuilds. Each completed shield scores one.',
    color: ReactColors.electricBlueBright,
    icon: Icons.layers_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.waveline: ReactVariantSpec(
    title: 'WAVELINE',
    badge: 'SIGNAL CHASE',
    subtitle: 'A moving pulse marks where action is valid.',
    detail: 'COMMAND + MOVING WINDOW',
    rules: 'A gesture command remains visible while a pulse travels across a signal line. Perform the command only as the pulse enters the central live window. Early or late input is a miss.',
    color: _pink,
    icon: Icons.monitor_heart_rounded,
  ),
  ReactVariantMode.splice: ReactVariantSpec(
    title: 'SPLICE',
    badge: 'MERGE READ',
    subtitle: 'Join split prompts into one correct action.',
    detail: 'TWO HALVES  •  ONE COMMAND',
    rules: 'Two command fragments approach from opposite sides. When they merge they reveal one complete gesture command. Read the combined prompt and perform it before the merged cue separates again.',
    color: _cyan,
    icon: Icons.call_merge_rounded,
  ),
  ReactVariantMode.thruster: ReactVariantSpec(
    title: 'THRUSTER',
    badge: 'BOOST CLIMB',
    subtitle: 'Momentum accelerates after every success.',
    detail: 'NO CEILING  •  SPEED SURGE',
    rules: 'Clear gesture commands continuously. Every success increases momentum and shortens both command time and transition delay. A miss drops momentum but costs a life.',
    color: _orange,
    icon: Icons.keyboard_double_arrow_up_rounded,
  ),
  ReactVariantMode.frostline: ReactVariantSpec(
    title: 'FROSTLINE',
    badge: 'COLD PRESSURE',
    subtitle: 'Delay too long and the arena freezes over.',
    detail: 'FROST BUILDS  •  FAST VENTS',
    rules: 'Frost accumulates while each command waits and carries into the next round. Fast clears melt some frost. Reach full freeze and the run ends.',
    color: ReactColors.electricBlueBright,
    icon: Icons.ac_unit_rounded,
  ),
  ReactVariantMode.pinpoint: ReactVariantSpec(
    title: 'PINPOINT',
    badge: 'TIGHT AIM',
    subtitle: 'Hit a shrinking center for maximum value.',
    detail: 'SHRINKING TARGET  •  PRECISION',
    rules: 'A target shrinks continuously. Tap as close to its centre as possible before it collapses. Centre hits score more and immediately launch a smaller, faster target.',
    color: ReactColors.lime,
    icon: Icons.gps_fixed_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.riftstep: ReactVariantSpec(
    title: 'RIFTSTEP',
    badge: 'SPACE SWAP',
    subtitle: 'Jump between split arenas at full speed.',
    detail: 'LEFT / RIGHT  •  TELEPORT READ',
    rules: 'The arena is split by a rift. Live targets teleport between left and right halves after every hit, sometimes feinting once before becoming active. Tap the active side before it collapses.',
    color: ReactColors.electricBlueBright,
    icon: Icons.compare_arrows_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.corridor: ReactVariantSpec(
    title: 'CORRIDOR',
    badge: 'TUNNEL FOCUS',
    subtitle: 'Prompts travel down narrowing lanes.',
    detail: 'DEPTH  •  NARROWING TUNNEL',
    rules: 'A live cue travels toward you through a corridor that narrows as it approaches. Tap it inside the bright strike band before it reaches the end of the tunnel.',
    color: _pink,
    icon: Icons.filter_center_focus_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.sidewinder: ReactVariantSpec(
    title: 'SIDEWINDER',
    badge: 'CURVE READ',
    subtitle: 'Targets snake through curved paths.',
    detail: 'SINE PATHS  •  TRACK MOTION',
    rules: 'A target snakes across the arena on a continuously changing curved path. Track and tap it before it exits. Each clear randomises wave frequency, amplitude, direction and speed.',
    color: ReactColors.lime,
    icon: Icons.gesture_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.hinge: ReactVariantSpec(
    title: 'HINGE',
    badge: 'PIVOT TIMING',
    subtitle: 'A rotating arm changes where cues can be hit.',
    detail: 'ROTATING ARM  •  MOVING ENDPOINT',
    rules: 'A rigid arm pivots around the arena centre with a live cue attached to its tip. Tap the moving endpoint before the arm completes its allowed rotations.',
    color: _orange,
    icon: Icons.rotate_right_rounded,
    mechanic: ReactVariantMechanic.target,
  ),
  ReactVariantMode.rampart: ReactVariantSpec(
    title: 'RAMPART',
    badge: 'ZONE GUARD',
    subtitle: 'Defend exposed zones while still reacting.',
    detail: '4 ZONES  •  DEFEND FAST',
    rules: 'Four shield zones surround the arena. One becomes exposed and starts taking damage. Tap the exposed zone to reinforce it before its shield breaks. Three broken shields end the run.',
    color: ReactColors.purple,
    icon: Icons.security_rounded,
    mechanic: ReactVariantMechanic.grid,
  ),
  ReactVariantMode.fadeout: ReactVariantSpec(
    title: 'FADEOUT',
    badge: 'LAST GLANCE',
    subtitle: 'Commands decay in visibility over time.',
    detail: 'READ EARLY  •  ACT FROM MEMORY',
    rules: 'A gesture command starts fully visible and continuously fades until completely invisible. Perform it before the timer expires; faster reads leave more safety margin.',
    color: _cyan,
    icon: Icons.blur_on_rounded,
  ),
};

ReactVariantSpec _legacySpec(ReactVariantMode mode) => ReactVariantSpec(
      title: mode.name.toUpperCase(),
      badge: 'ARCHIVED LAB',
      subtitle: 'Stored in the experimental mode library.',
      detail: 'DISABLED  •  AVAILABLE FOR FUTURE TESTING',
      rules: 'This experimental mode is currently switched off. Its enum identity is retained so existing local records remain compatible.',
      color: ReactColors.electricBlueBright,
      icon: Icons.science_outlined,
      enabled: false,
    );

extension ReactVariantModeUi on ReactVariantMode {
  ReactVariantSpec get spec => _activeSpecs[this] ?? _legacySpec(this);

  String get id => name;
  String get title => spec.title;
  String get badge => spec.badge;
  String get subtitle => spec.subtitle;
  String get detail => spec.detail;
  String get rules => spec.rules;
  Color get color => spec.color;
  IconData get icon => spec.icon;
  ReactVariantMechanic get mechanic => spec.mechanic;
  bool get enabled => spec.enabled;

  static List<ReactVariantMode> get enabledModes => ReactVariantMode.values
      .where((mode) => mode.enabled)
      .toList(growable: false);
}
